# Generated by Django 5.1.7 on 2025-07-20 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer_app', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyzer_app.userprofile'),
        ),
    ]
