# Generated by Django 5.1.7 on 2025-07-20 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer_app', '0003_alter_report_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='diseases_detected',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='extracted_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='medicine_suggestions',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
