# Generated by Django 5.1.7 on 2025-07-26 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer_app', '0004_alter_report_diseases_detected_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('question', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
